services:
  geth:
    image: ghcr.io/bnb-chain/bsc:1.6.7
    container_name: bsc-geth
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/rpc_nodes/bsc-data/full:/data
      - ./config.toml:/bsc/config/config.toml:ro
      - ./genesis.json:/bsc/config/genesis.json:ro
    command:
      - --datadir=/data
      - --cache=8000
      - --rpc.allow-unprotected-txs
      - --history.transactions=0
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
